version: '3.8'

networks:
  luby_project:
    external: true

volumes:
  db-data:

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic-test:1:1,:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "3333:3333"
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    networks:
      - luby_project
    depends_on:
      - mysql

  mysql:
    build:
      context: ./docker/db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prova_adonis
    ports:
      - "3307:3307"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - luby_project